services:
  db2-mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: tcdb
      MYSQL_USER: tcdb
      MYSQL_PASSWORD: ${DB_PASSWD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWD}
    volumes:
      - ./.data:/var/lib/mysql
    ports:
      - 127.0.0.1:${DB_PORT}:3306
