services:
  vert-sys-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: tkdb
      MYSQL_USER: tkdb
      MYSQL_PASSWORD: ${DB_PASSWD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWD}
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 127.0.0.1:${DB_PORT}:3306
